---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: app-api
spec:
  selector:
    matchLabels:
      app: app-api
  replicas: 2
  template:
    metadata:
      labels:
        app: app-api
    spec:
      containers:
        - name: social-media-2024-v1-app-api
          image: soyeb88/social-media-2024-v1:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8086
---
apiVersion: v1
kind: Service
metadata:
  name: social-media-2024-v1-app-api-service
spec:
  selector:
    app: app-api
  ports:
    - port: 8086
      nodePort: 30001
      protocol: TCP
      targetPort: 8084
  type: NodePort
